local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.MARBLEBEAN = "Marble Bean"
STRINGS.RECIPE_DESC.MARBLEBEAN = "Grow a marble forest."
STRINGS.NAMES.MARBLEBEAN_SAPLING = "Marble Sprout"
STRINGS.NAMES.MARBLESHRUB = "Marble Shrub"

-- Character strings, no WES or WILBUR since they don't talk.
-- Remove DST-only characters: WALTER WANDA WINONA WORTOX WURT 
-- Need to add DS-only: WAGSTAFF WALANI WARBUCKS WHEELER WILBA WOODLEGS 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MARBLEBEAN = "I traded the old family cow for it."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MARBLEBEAN_SAPLING = "It looks carved."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MARBLESHRUB = "Makes sense to me."

STRINGS.CHARACTERS.WARLY.DESCRIBE.MARBLEBEAN = "I don't think this bean is edible."
STRINGS.CHARACTERS.WARLY.DESCRIBE.MARBLEBEAN_SAPLING = "Just a petite marble bébé."
STRINGS.CHARACTERS.WARLY.DESCRIBE.MARBLESHRUB = "If marble beans can grow, maybe they can be eaten."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MARBLEBEAN = "Fee fi fo fum!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MARBLESHRUB = "Tis a shrub of stone!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MARBLEBEAN_SAPLING = "How dost thou grow?"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MARBLEBEAN = "Let me guess, it grows a marble stalk?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MARBLEBEAN_SAPLING = "Stone cold growth."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MARBLESHRUB = "I've found a shrubbery."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.MARBLEBEAN = "Bean there, done that!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MARBLEBEAN_SAPLING = "You can plant anything in the ground!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MARBLESHRUB = "That's a weird shape for a bush."

STRINGS.CHARACTERS.WENDY.DESCRIBE.MARBLEBEAN = "Cold... but not lifeless..."
STRINGS.CHARACTERS.WENDY.DESCRIBE.MARBLEBEAN_SAPLING = "It cares nothing for the laws of this world..."
STRINGS.CHARACTERS.WENDY.DESCRIBE.MARBLESHRUB = "Against all odds, it has flourished in life..."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MARBLEBEAN = "Marble growth is arboriculturally impossible."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MARBLEBEAN_SAPLING = "I believe it's a perennial."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MARBLESHRUB = "Not ideal for topiary."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.MARBLEBEAN = "I guess we just... plant it? In the dirt?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MARBLEBEAN_SAPLING = "That makes no sense!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MARBLESHRUB = "What sort of bush doesn't burn?!"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MARBLEBEAN = "Brainlady says is not for eat."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MARBLEBEAN_SAPLING = "Rock bush is growing!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MARBLESHRUB = "Rock is strongest bush!"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.MARBLEBEAN = "The magical fruit."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MARBLEBEAN_SAPLING = "Well, lookit that. It sprouted."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MARBLESHRUB = "Defo can't chop that."

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MARBLEBEAN = "Hard Bean."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MARBLEBEAN_SAPLING = "Little Stone Friend!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MARBLESHRUB = "Stone Friend Big Now."

STRINGS.CHARACTERS.WX78.DESCRIBE.MARBLEBEAN = "INFURIATINGLY ILLOGICAL"
STRINGS.CHARACTERS.WX78.DESCRIBE.MARBLEBEAN_SAPLING = "IS IT ORGANIC OR INORGANIC?"
STRINGS.CHARACTERS.WX78.DESCRIBE.MARBLESHRUB = "INFERIORITY ASSESSMENT: INCONCLUSIVE"

-- DS-only
STRINGS.CHARACTERS.WAGSTAFF.DESCRIBE.MARBLEBEAN = "A lithic seed specimen. Preposterous... yet full of potential."
STRINGS.CHARACTERS.WAGSTAFF.DESCRIBE.MARBLEBEAN_SAPLING = "Vegetative growth without soil dependence. Fascinating."
STRINGS.CHARACTERS.WAGSTAFF.DESCRIBE.MARBLESHRUB = "A fully developed marble growth. Classification remains elusive."

STRINGS.CHARACTERS.WALANI.DESCRIBE.MARBLEBEAN = "Yeah, I wouldn't try eatin' that, dude."
STRINGS.CHARACTERS.WALANI.DESCRIBE.MARBLEBEAN_SAPLING = "No way. It's actually growin'."
STRINGS.CHARACTERS.WALANI.DESCRIBE.MARBLESHRUB = "A rock bush. Weird, but kinda cool."

STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.MARBLEBEAN = "A bean of stone. How very impractical."
STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.MARBLEBEAN_SAPLING = "It appears to be growing. Absurd."
STRINGS.CHARACTERS.WARBUCKS.DESCRIBE.MARBLESHRUB = "A marble shrub. Decorative, if nothing else."

STRINGS.CHARACTERS.WHEELER.DESCRIBE.MARBLEBEAN = "A bean made of stone. Figures."
STRINGS.CHARACTERS.WHEELER.DESCRIBE.MARBLEBEAN_SAPLING = "It's growing. It shouldn't be."
STRINGS.CHARACTERS.WHEELER.DESCRIBE.MARBLESHRUB = "A marble shrub. This place is ridiculous."

STRINGS.CHARACTERS.WILBA.DESCRIBE.MARBLEBEAN = "'TIS HARD BEAN"
STRINGS.CHARACTERS.WILBA.DESCRIBE.MARBLEBEAN_SAPLING = "LITTLE ROCK TREE GROWS"
STRINGS.CHARACTERS.WILBA.DESCRIBE.MARBLESHRUB = "'TIS BUSH O' ROCK"

STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.MARBLEBEAN = "Arr, a bean o' stone. The sea's got stranger, but not by much."
STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.MARBLEBEAN_SAPLING = "Growin' like a cursed splinter, it be."
STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.MARBLESHRUB = "A bush o' marble. Worthless, 'less ye need cover fer plunder."